name: Sync branches
on:
  push:
jobs:
  dev:
    name: Nightly Merge
    runs-on: ubuntu-16.04
    steps:
    - uses: robotology/gh-action-nightly-merge@v1.2.0
      with:
          development_branch: 'dev'
          push_token: ${{ secrets.GITHUB_TOKEN }}
  demo:
    name: Nightly Merge dev
    runs-on: ubuntu-16.04
    steps:
    - uses: robotology/gh-action-nightly-merge@v1.2.0
      with:
          development_branch: 'demo'
          push_token: ${{ secrets.GITHUB_TOKEN }}
