name: Sync branches
on:
  push:
jobs:
  dev:
    name: Nightly Merge
    runs-on: ubuntu-16.04
    steps:
      - uses: robotology/gh-action-nightly-merge@v1.2.0
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          development_branch: dev
      - uses: robotology/gh-action-nightly-merge@v1.2.0
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          development_branch: demo
          push_token: ${{ secrets.GITHUB_TOKEN }}
